name: eslint-strict

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: |
        yarn install --frozen-lockfile
    - name: eslint
      uses: reviewdog/action-eslint@v1
      with:
        reporter: github-pr-review
        eslint_flags: '--ext .ts --ignore-path .gitignore . --config ./.eslintrc.strict.js'